#!/bin/bash

player='omxplayer' # default valid for pi

conf_file=~/.play.conf
[[ -f $conf_file ]] && source $conf_file

if [[ "$1" == "--autoplay" ]]; then
  autoplay="$1"
  shift
fi

src="$*"
while read id; do # Loop in case we are reading a playlist
  url="https://www.youtube.com/watch?v=$id"
  title=$(youtube-dl -e "$url")
  echo -e "Playing: $title ($url)"

  # Record history
  ts=$(date '+%s')
  date=$(date '+%Y-%m-%d %H:%M:%S')
  [[ "$record_history" == "true" ]] && echo -e "$ts\t$date\t$video\t$title" >> "$history_file"

  # Play
  [[ "$audio_only" == "true" ]] && format="bestaudio" || format="mp4"
  stream=$(youtube-dl -g -f $format "$url")
  ${player} "$stream" > /dev/null 2>&1 </dev/tty
  exit_code=$?
  # For playlists: break the loop if the video is stopped with a ctrl-c or error
  [[ $exit_code != 0 && $exit_code != 3 ]] && break # omxplayer exits with 0 when stopped with 'q'
done < <(youtube-dl --get-id "$src")

yousearch $autoplay "$src"
