#!/bin/bash

conf_file=~/.play.conf
[[ -f $conf_file ]] && source $conf_file

if [[ "$1" == "--autoplay" ]]; then
  autoplay="$1"
  shift
fi

src=$1

# play
omxplayer -b -o local $(youtube-dl -g -f best "$src")
yousearch $autoplay $1
