---
- hosts: pib
  tasks:
  - name: install apt packages
    apt: name={{item}} state=latest
    with_items:
      - omxplayer
      - libxml2-utils
      - python-pip
      - python3-pip
    become: true

  - name: install pip packages
    pip: name={{item}} state=latest
    with_items:
      - youtube-dl
    become: true

  - name: Create /opt/youplay
    file: path=/opt/youplay owner=root group=root mode=0755 state=directory
    become: true

  - name: install youplay files in /opt/youplay/
    copy: src={{item}} dest=/opt/youplay/{{item}} owner=root group=root mode=0755 backup=yes
    with_items:
      - youplay
      - yousearch
      - youplay_args
      - youplay.conf
    become: true

  - name: symlink youplay and yousearch in /usr/local/bin/
    file: src=/opt/youplay/{{item}} dest=/usr/local/bin/{{item}} owner=root group=root mode=0755 state=link
    with_items:
      - youplay
      - yousearch
    become: true

  - name: set omxplayer as default player
    lineinfile: dest=/opt/youplay/youplay.conf line='export player="omxplayer -b -o local"'
    become: true

  - name: set default format to mp4
    lineinfile: dest=/opt/youplay/youplay.conf line='export video_format=mp4'
    become: true
